function validate_detect_artifacts_mex()
%VALIDATE_DETECT_ARTIFACTS_MEX  Parity gate: detect_artifacts_mex vs MATLAB
% detect_artifacts(..., 'slope_test', false), on the synthetic-EEG battery.
%
% Fixtures (.npy) generated by the DYNAM-O Desktop App's
% scripts/generate_handoff_fixtures.m and staged under the system temporary
% directory at handoff_fixtures/sim/. Per-variant sample-disagreement
% budgets match what we shipped in preraulab/artifact_detection PR #1.

    fix_dir = fullfile(tempdir, 'handoff_fixtures', 'sim');
    rust_bridge_dir = fileparts(mfilename('fullpath'));
    dynamo_root = fileparts(rust_bridge_dir);
    addpath(genpath(fullfile(dynamo_root, 'toolbox')));

    variants = { ...
        'clean',  42, 5;  ...
        'motion', 42, 30; ...
        'flat',   42, 5;  ...
        'full',   42, 30; ...
        'dense',  43, 50; ...
    };

    fail = false;
    for vi = 1:size(variants, 1)
        v = variants{vi, 1}; s = variants{vi, 2}; budget = variants{vi, 3};

        base    = sprintf('sim_%s_seed%d', v, s);
        data    = readNPY_or_npy(fullfile(fix_dir, [base '.npy']));
        mat_msk = readNPY_or_npy(fullfile(fix_dir, [base '_art_mat_no_slope.npy']));
        data    = double(data(:));
        mat_msk = logical(mat_msk(:));
        Fs      = 100;

        rs_msk  = detect_artifacts_mex(data, Fs);

        n_diff  = sum(rs_msk ~= mat_msk);
        if n_diff > budget
            fail = true;
            % Show first 10 mismatched indices for triage.
            idx = find(rs_msk ~= mat_msk, 10, 'first');
            fprintf('  %-8s : %5d disagreements (budget %3d)  FAIL  first10=%s\n', ...
                v, n_diff, budget, mat2str(idx(:).'));
        else
            fprintf('  %-8s : %5d disagreements (budget %3d)  PASS\n', ...
                v, n_diff, budget);
        end
    end

    if fail
        error('validate_detect_artifacts_mex:fail', ...
            'One or more variants exceeded sample-disagreement budget.');
    else
        fprintf('All variants within budget.\n');
    end
end

function arr = readNPY_or_npy(path)
% Tiny .npy reader. Handles f64 and bool '|b1'/'|u1' dtypes.
    fid = fopen(path, 'r'); raw = fread(fid, inf, '*uint8'); fclose(fid);
    if numel(raw) < 10 || ~isequal(raw(1:6).', uint8([147 78 85 77 80 89]))  % \x93NUMPY
        error('not an .npy file: %s', path);
    end
    hdr_len = double(typecast(raw(9:10), 'uint16'));
    hdr     = char(raw(11:10 + hdr_len).');
    data    = raw(11 + hdr_len:end);
    if contains(hdr, '''<f8''')
        arr = typecast(data, 'double');
    elseif contains(hdr, '''|b1''') || contains(hdr, '''|u1''')
        arr = uint8(data); arr = logical(arr);
    else
        error('unsupported npy dtype in %s: %s', path, hdr);
    end
end
