function html = buildHeaderStripHtml(~)
%BUILDHEADERSTRIPHTML  Numbered-steps onboarding strip for the
%channels & references composer (createRunMontageWindow). Three
%coloured chips arranged left → middle → right, aligned with the
%columns underneath so the workflow reads naturally:
%   1. Pick channels      2. Build output      3. Save and Close
%
%Returns a self-contained HTML document suitable for a uihtml HTMLSource.

    html = ['<!doctype html><html><head><style>' ...
        'html,body{margin:0;padding:0;height:100%;width:100%;background:#fafbfc;' ...
        'font-family:"Segoe UI",Tahoma,sans-serif;color:#2c3e50;}' ...
        '.row{display:flex;align-items:stretch;justify-content:space-between;' ...
        'height:100%;padding:8px 4px;box-sizing:border-box;gap:6px;}' ...
        '.step{flex:1;display:flex;align-items:center;padding:0 14px;' ...
        'border-radius:6px;border:1px solid #d4dae1;background:#ffffff;' ...
        'box-shadow:0 1px 2px rgba(0,0,0,0.04);}' ...
        '.num{display:inline-flex;align-items:center;justify-content:center;' ...
        'width:24px;height:24px;border-radius:50%;background:#1971b9;color:#fff;' ...
        'font-weight:700;font-size:13px;margin-right:10px;flex-shrink:0;}' ...
        '.label{font-size:13px;line-height:1.2;}' ...
        '.label b{font-weight:700;}' ...
        '.arrow{color:#9aa6b3;font-size:22px;align-self:center;flex-shrink:0;' ...
        'padding:0 2px;}' ...
        '</style></head><body><div class="row">' ...
        '<div class="step"><span class="num">1</span><span class="label">' ...
        '<b>Pick</b> channels on the left<br>(or <b>+ Mean / + Difference / + Custom</b> for derived)</span></div>' ...
        '<span class="arrow">›</span>' ...
        '<div class="step"><span class="num">2</span><span class="label">' ...
        '<b>Add</b> to output rows<br>using the middle buttons</span></div>' ...
        '<span class="arrow">›</span>' ...
        '<div class="step"><span class="num">3</span><span class="label">' ...
        '<b>Review</b> on the right,<br>then click Save and Close</span></div>' ...
        '</div></body></html>'];
end
