function buildOptionsStruct(app)
    % buildOptionsStruct  Package DYNAMO option structs into indexed cell arrays.
    %
    %   Reads the option structs from the DYNAMO base class properties and
    %   stores them in app.options_structs alongside their names in
    %   app.struct_names for use in logging and processing.

    app.struct_names    = {'SOPH_options','baseline_options','detection_options', ...
        'param_basis_power_options','param_basis_phase_options', ...
        'spline_basis_power_options','spline_basis_phase_options'};
    app.options_structs = { app.SOPH_options, ...
        app.baseline_options, ...
        app.detection_options, ...
        app.param_basis_power_options, ...
        app.param_basis_phase_options, ...
        app.spline_basis_power_options, ...
        app.spline_basis_phase_options };
end
