function S = collectBatchSettings(app)
    % collectBatchSettings  Snapshot the GUI batch-level state into a struct.
    %
    %   S = collectBatchSettings(app)
    %
    %   Returns a struct that captures every user-configurable batch-run
    %   field shown in the DYNAM-O Batch Run tab — data/staging file lists,
    %   output dir, save toggles, format dropdowns, channel/reference,
    %   staging CSV config, stage label mappings, and runtime options.
    %   No UI side effects.
    %
    %   The struct round-trips through generate_run_log / load_run_log and
    %   applyBatchSettings, so it is the canonical "reloadable batch
    %   settings" payload.
    %
    %   See also: applyBatchSettings, generate_run_log, load_run_log.
    %
    % =====================================================================
    %                   DYNAM-O Toolbox  |  Prerau Laboratory
    % =====================================================================

    S = struct();

    % Force row cellstr so the JSON encoder writes a flat array.
    S.data_files    = reshape(cellstr(app.DataList),    1, []);
    S.staging_files = reshape(cellstr(app.StagingList), 1, []);
    S.output_dir    = char(app.OutputDirEditField.Value);
    S.metadata_file = char(app.MetadataFile_);

    S.save_toggles = struct( ...
        'save_logs',           logical(app.SaveLogsSwitch.Value), ...
        'save_spline_images',  logical(app.SaveSplineImagesCheckBox.Value), ...
        'save_param_images',   logical(app.SaveParamImagesCheckBox.Value), ...
        'save_data_summary',   logical(app.SaveDataSummaryCheckBox.Value), ...
        'save_aux_data',       logical(app.SaveAuxDataCheckBox.Value), ...
        'save_spline_basis',   logical(app.SaveSplineBasisCheckBox.Value), ...
        'save_param_basis',    logical(app.SaveParamBasisCheckBox.Value), ...
        'save_sophs',          logical(app.SaveSOPHsCheckBox.Value), ...
        'save_peak_stats',     logical(app.SavePeakStatsCheckBox.Value));

    S.formats = struct( ...
        'spline_figures',      char(app.SplineFiguresDropDown.Value), ...
        'parametric_figures',  char(app.ParametricFiguresDropDown.Value), ...
        'data_summary',        char(app.DataSummaryDropDown.Value), ...
        'auxiliary_data',      char(app.AuxiliaryDataDropDown.Value), ...
        'spline_basis',        char(app.SplineBasisDropDown.Value), ...
        'parametric_basis',    char(app.ParametricBasisDropDown.Value), ...
        'so_power_histograms', char(app.SOPowerHistogramsDropDown.Value), ...
        'peak_stats_table',    char(app.PeakStatsTableDropDown.Value));

    S.runtime = struct( ...
        'overwrite_existing', logical(app.OverwriteExistingFilesCheckBox.Value), ...
        'run_in_reverse',     logical(app.RunInReverse.Value));

    S.channels = struct( ...
        'channel_spec',   char(app.ChannelEditField.Value), ...
        'reference_spec', char(app.ReferenceEditField.Value));

    S.staging_config = struct( ...
        'delimiter',     char(app.DelimeterOptionField.Value), ...
        'header_rows',   double(app.HeaderRowsEditField.Value), ...
        'times_column',  double(app.TimesColumnEditField.Value), ...
        'stages_column', double(app.StagesColumnEditField.Value), ...
        'resample_on',   logical(app.ResampleSwitch.Value), ...
        'resample_fs',   double(app.ResampleFsEditField.Value));

    S.stage_labels = struct( ...
        'Wake',     char(app.WakeEditField.Value), ...
        'REM',      char(app.REMEditField.Value), ...
        'N1',       char(app.N1EditField.Value), ...
        'N2',       char(app.N2EditField.Value), ...
        'N3',       char(app.N3EditField.Value), ...
        'Unknown',  char(app.UnknownEditField.Value), ...
        'Artifact', char(app.ArtifactEditField.Value));
end
