function fig = showSplashScreen(app)
%SHOWSPLASHSCREEN  Borderless logo + version + credit window shown
%during app construction. Returns the uifigure handle so the caller can
%delete it once the main app becomes visible.

    sc = get(0, 'ScreenSize');
    w = 600; h = 420;
    pos = [round((sc(3)-w)/2), round((sc(4)-h)/2), w, h];

    fig = uifigure( ...
        'Name', 'DYNAM-O', ...
        'Position', pos, ...
        'Resize', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'WindowStyle', 'normal', ...
        'Color', [1 1 1]);
    fig.HandleVisibility = 'off';

    svg = app.buildLogoSvg('width', 520);
    ver = dynamo_version();

    html = ['<!doctype html><html><head>' ...
        '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Saira:wght@400;700&display=swap">' ...
        '<style>' ...
        'html,body{margin:0;padding:0;height:100%;width:100%;background:#fff;' ...
        'font-family:"Helvetica Neue",Arial,sans-serif;color:#222;}' ...
        '.wrap{display:flex;flex-direction:column;align-items:center;' ...
        'justify-content:center;height:100%;padding:24px;box-sizing:border-box;}' ...
        '.logo{width:520px;max-width:90%;}' ...
        '.version{color:#1971b9;font-size:13px;margin-top:8px;' ...
        'font-family:Menlo,Consolas,"Courier New",monospace;}' ...
        '.credit{font-size:14px;margin-top:22px;text-align:center;line-height:1.7;}' ...
        '.credit a{color:#1971b9;text-decoration:none;}' ...
        '</style></head><body><div class="wrap">' ...
        '<div class="logo">' svg '</div>' ...
        '<div class="version">Version: ' ver '</div>' ...
        '<div class="credit">' ...
        'Developed by the Prerau Laboratory<br>' ...
        '<a href="https://sleepeeg.org">sleepeeg.org</a> · ' ...
        '<a href="https://prerau.bwh.harvard.edu/dynam-o/">prerau.bwh.harvard.edu/dynam-o</a><br>' ...
        '<a href="https://github.com/preraulab/DYNAM-O">github.com/preraulab/DYNAM-O</a>' ...
        '</div></div></body></html>'];

    g = uigridlayout(fig, [1 1], 'Padding', [0 0 0 0], 'BackgroundColor', [1 1 1]);
    uihtml(g, 'HTMLSource', html);

    % Stamp the start time so closeSplashScreen can enforce a minimum
    % visible lifetime even if the rest of construction completes
    % quickly.
    fig.UserData = struct('startTic', tic, 'minLifetimeSec', 2.0);
    drawnow;
end

