function html = buildLoadingAnimationHtml(~, caption)
    %LOADINGANIMATIONHTML  Build the centered HTML wrapper around
    %   the dancing-bars SVG (the same one set_running puts on the
    %   RUN button). Used by both the preview pane placeholder and
    %   the file-tree loading overlay so the GUI's "something is
    %   churning" cue is consistent everywhere.
    %
    %   `caption` is shown beneath the bars (e.g. 'Loading…').
    %   Pass '' to omit.
    if nargin < 2, caption = ''; end
    % SVG copied verbatim from set_running so updates to either
    % stay coupled. The `currentColor` fill picks up the CSS
    % color we set on the wrapper div.
    svg = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 135 140" ', ...
           'fill="currentColor" style="width:96px;height:96px;">', ...
           '<rect y="10" width="15" height="120" rx="6">', ...
           '<animate attributeName="height" begin="0.5s" dur="1s" ', ...
           'values="120;110;100;90;80;70;60;50;40;140;120" calcMode="linear" repeatCount="indefinite"/>', ...
           '<animate attributeName="y" begin="0.5s" dur="1s" ', ...
           'values="10;15;20;25;30;35;40;45;50;0;10" calcMode="linear" repeatCount="indefinite"/>', ...
           '</rect>', ...
           '<rect x="30" y="10" width="15" height="120" rx="6">', ...
           '<animate attributeName="height" begin="0.25s" dur="1s" ', ...
           'values="120;110;100;90;80;70;60;50;40;140;120" calcMode="linear" repeatCount="indefinite"/>', ...
           '<animate attributeName="y" begin="0.25s" dur="1s" ', ...
           'values="10;15;20;25;30;35;40;45;50;0;10" calcMode="linear" repeatCount="indefinite"/>', ...
           '</rect>', ...
           '<rect x="60" width="15" height="140" rx="6">', ...
           '<animate attributeName="height" begin="0s" dur="1s" ', ...
           'values="120;110;100;90;80;70;60;50;40;140;120" calcMode="linear" repeatCount="indefinite"/>', ...
           '<animate attributeName="y" begin="0s" dur="1s" ', ...
           'values="10;15;20;25;30;35;40;45;50;0;10" calcMode="linear" repeatCount="indefinite"/>', ...
           '</rect>', ...
           '<rect x="90" y="10" width="15" height="120" rx="6">', ...
           '<animate attributeName="height" begin="0.25s" dur="1s" ', ...
           'values="120;110;100;90;80;70;60;50;40;140;120" calcMode="linear" repeatCount="indefinite"/>', ...
           '<animate attributeName="y" begin="0.25s" dur="1s" ', ...
           'values="10;15;20;25;30;35;40;45;50;0;10" calcMode="linear" repeatCount="indefinite"/>', ...
           '</rect>', ...
           '<rect x="120" y="10" width="15" height="120" rx="6">', ...
           '<animate attributeName="height" begin="0.5s" dur="1s" ', ...
           'values="120;110;100;90;80;70;60;50;40;140;120" calcMode="linear" repeatCount="indefinite"/>', ...
           '<animate attributeName="y" begin="0.5s" dur="1s" ', ...
           'values="10;15;20;25;30;35;40;45;50;0;10" calcMode="linear" repeatCount="indefinite"/>', ...
           '</rect>', ...
           '</svg>'];
    captionHtml = '';
    if ~isempty(caption)
        captionHtml = sprintf( ...
            '<div style="margin-top:14px;font-size:13px;color:#8a939e;">%s</div>', ...
            caption);
    end
    html = ['<!DOCTYPE html><html><head><style>', ...
            'html,body{margin:0;padding:0;height:100%;background:white;}', ...
            '.wrap{display:flex;flex-direction:column;align-items:center;', ...
                  'justify-content:center;height:100%;color:#5a98c0;', ...
                  'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}', ...
            '</style></head><body>', ...
            '<div class="wrap">', svg, captionHtml, '</div>', ...
            '</body></html>'];
end
