function createBottomBar(app)
    %createBottomBar  Build the persistent bottom strip on the Setup
    %   tab: status text panel, RUN/STOP batch buttons, time-estimate /
    %   help cluster, and the progress bar.
    % progress bar + Help. The middle column hosts RunBatchGrid
    % with three equal-flex sub-columns (STOP, RUN, toggles).
    app.BottomGrid             = uigridlayout(app.FullDYNAMOSetupGrid);
    app.BottomGrid.ColumnWidth = {'1x', '1x', '1x'};
    app.BottomGrid.RowHeight = {'1x'};   % ~4 stacked buttons tall
    app.BottomGrid.ColumnSpacing = 0;
    app.BottomGrid.RowSpacing  = 0;
    app.BottomGrid.Layout.Row  = 2;
    app.BottomGrid.Layout.Column = 1;

    % ---- Column 1: Status text ----
    % Label gets a tight fixed height; the TextArea ('1x') fills
    % the rest of the bottom-row height so long run logs have as
    % much vertical room as possible. Vertical scrolling is
    % handled by CSSuiTextArea (Scroll = true below).
    app.StatusTextGrid             = uigridlayout(app.BottomGrid);
    app.StatusTextGrid.ColumnWidth = {'1x'};
    app.StatusTextGrid.RowHeight = {18, '1x'};
    app.StatusTextGrid.ColumnSpacing = 0;
    app.StatusTextGrid.RowSpacing  = 2;
    app.StatusTextGrid.Padding     = [0 0 0 0];
    app.StatusTextGrid.Layout.Row  = 1;
    app.StatusTextGrid.Layout.Column = 1;

    app.StatusLabel = CSSuiLabel(app.StatusTextGrid, ...
        'Style', 'shadow_light', ...
        'FontSize', '13px', ...
        'Text', 'STATUS:' ...
        );
    app.StatusLabel.Layout.Row    = 1;
    app.StatusLabel.Layout.Column = 1;

    app.TextArea = CSSuiTextArea(app.StatusTextGrid, ...
        'Style', 'shadow_light', ...
        'Editable', false, ...
        'Color', '#414c57',...
        'FontWeight','600',...
        'BackgroundColor','#ffffff'...
        );
    app.TextArea.Scroll = true;
    app.TextArea.Row   = 2;
    app.TextArea.Column = 1;
    app.TextArea.Value = {'Add files, select settings, and press ''Run Batch'' to run'};

    % ---- Column 2: Run / Stop buttons ----
    buttonicon_size = '1.5em';

    % Five columns: flex | STOP | RUN | toggles (fixed) | flex.
    %   - STOP / RUN cells are flex ('1x' each) so the buttons
    %     resize with the figure.
    %   - Toggles cell is pinned to 200 px so the iframe always
    %     has room for the full "Reverse" / "Overwrite" labels.
    %   - The two outer '0.5x' flex spacers keep the entire
    %     STOP-RUN-toggles block centred inside the middle
    %     BottomGrid column.
    app.RunBatchGrid             = uigridlayout(app.BottomGrid);
    app.RunBatchGrid.ColumnWidth = {'0.5x', '1x', '1x', 200, '0.5x'};
    app.RunBatchGrid.RowHeight   = {'1x'};
    app.RunBatchGrid.ColumnSpacing = 0;
    app.RunBatchGrid.Padding = [0 0 0 0];
    app.RunBatchGrid.Layout.Row  = 1;
    app.RunBatchGrid.Layout.Column = 2;

    app.StopBatchButton = CSSuiButton(app.RunBatchGrid, ...
        'Style', 'shadow', ...
        'Shape','circle',...
        'Text', 'STOP', ...
        'MaxHeight', '100px',...
        'BackgroundColor', '#f5e8e9', ...
        'ButtonPushedFcn', createCallbackFcn(app, @StopBatchButtonPushed, true), ...
        'Icon', '<rect x="5" y="5" width="14" height="14"/>', ...
        'IconPosition', 'top', ...
        'IconSize',buttonicon_size, ...
        'Padding','10px',...
        'Height', '80%',...
        'Width', '80%',...
        'FontSize', '15px', ...
        'IconOnlyWidth', '80px',...
        'Enabled', false ...
        );
    app.StopBatchButton.Row    = 1;
    app.StopBatchButton.Column = 2;
    app.StopBatchButton.HTMLComponent.Tooltip = 'Stop batch run after completion of current file';

    app.RunBatchButton = CSSuiButton(app.RunBatchGrid, ...
        'Style', 'shadow', ...
        'Shape','circle',...
        'Text', 'RUN', ...
        'MaxHeight', '100px',...
        'ButtonPushedFcn', createCallbackFcn(app, @RunBatchButtonPushed, true), ...
        'Icon', '<path d="M8 5v14l11-7z"/>', ...
        'IconPosition', 'top', ...
        'IconSize',buttonicon_size, ...
        'BackgroundColor', '#e8f5e9', ...
        'Padding','10px',...
        'Height', '80%',...
        'Width', '80%',...
        'IconOnlyWidth', '80px',...
        'FontSize', '15px', ...
        'Enabled', true ...
        );
    app.RunBatchButton.Row    = 1;
    app.RunBatchButton.Column = 3;
    app.RunBatchButton.HTMLComponent.Tooltip = 'Batch run DYNAM-O';

    % Switches: 4-row inner grid, spacers on rows 1 & 4 push
    % the two switches to the vertical centre. Lives inside
    % RunBatchGrid as col 3 alongside STOP and RUN.
    % NOTE: 'fit' cannot be used with uihtml-based components —
    % explicit pixel heights are required instead.
    app.RunBatchOptionsGrid             = uigridlayout(app.RunBatchGrid);
    app.RunBatchOptionsGrid.ColumnWidth = {'1x'};
    app.RunBatchOptionsGrid.RowHeight   = {'1x', '1x'};
    app.RunBatchOptionsGrid.RowSpacing  = 4;
    app.RunBatchOptionsGrid.Padding     = [0 4 0 4];
    app.RunBatchOptionsGrid.Layout.Row  = 1;
    app.RunBatchOptionsGrid.Layout.Column = 4;

    % Stack the label above the toggle (column-reverse: HTML
    % puts the toggle before the label, so reversing the column
    % direction lifts the label to the top). Tightens gap and
    % drops left/right padding so the iframe content centres
    % cleanly under the narrow stacked layout.
    switchStackCSS = ['#css-root{flex-direction:column-reverse;' ...
                      'align-items:center;justify-content:center;' ...
                      'gap:2px;padding:0;}' ...
                      '.css-label{font-size:12px;}'];
    app.RunInReverse = CSSuiSwitch(app.RunBatchOptionsGrid, ...
        'Style', 'shadow', ...
        'Text', 'Reverse', ...
        'CSS', switchStackCSS, ...
        'Enabled', true ...
        );
    app.RunInReverse.Row    = 1;
    app.RunInReverse.Column = 1;
    app.RunInReverse.HTMLComponent.Tooltip = 'Check to run through batch files from bottom to top. This is useful when running two instances of the manager in parallel on the same dataset';

    app.OverwriteExistingFilesCheckBox = CSSuiSwitch(app.RunBatchOptionsGrid, ...
        'Style', 'shadow', ...
        'Text', 'Overwrite', ...
        'CSS', switchStackCSS, ...
        'Enabled', true ...
        );
    app.OverwriteExistingFilesCheckBox.Row    = 2;
    app.OverwriteExistingFilesCheckBox.Column = 1;
    app.OverwriteExistingFilesCheckBox.HTMLComponent.Tooltip = 'By default, output files will automatically be skipped if already generated. Check to overwrite all files.';

    % Progress bar (flex — shrinks first when figure narrows)
    % and Help (fixed). Parent BottomGrid col 3 is '1x' flex, so
    % the bar absorbs all the give-and-take while Help stays at
    % 100 px and the switches in col 2 stay at full size.
    app.TimeEstimateGrid             = uigridlayout(app.BottomGrid);
    app.TimeEstimateGrid.ColumnWidth = {'1x', 100};
    app.TimeEstimateGrid.RowHeight   = {'1x'};
    app.TimeEstimateGrid.ColumnSpacing = 15;
    app.TimeEstimateGrid.Padding     = [0 5 5 5];
    app.TimeEstimateGrid.Layout.Row  = 1;
    app.TimeEstimateGrid.Layout.Column = 3;

    app.HelpButton = CSSuiButton(app.TimeEstimateGrid, ...
        'Style', 'shadow', ...
        'Text', 'Help', ...
        'Height', '60px',...
        'Icon', ['<path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z' ...
        'M13 19h-2v-2h2v2z' ...
        'M15.07 11.25l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83' ...
        'l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8' ...
        'c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/>'],...
        'IconPosition','left',...
        'IconSize','1.5em',...
        'ButtonPushedFcn', @(src,event) showHelpButtonPushed(app) ...
        );
    app.HelpButton.Row    = 1;
    app.HelpButton.Column = 2;

    app.ProgressBar = SmoothProgressBar(app.TimeEstimateGrid, ...
        'BarHeight',       0.35, ...
        'BarBorderRadius', '999px', ...
        'BorderRadius',    '999px', ...
        'TextPosition',    'above', ...
        'Text',            '', ...
        'Enabled',         false);
    app.ProgressBar.Layout.Row    = 1;
    app.ProgressBar.Layout.Column = 1;
end
