function createBatchSetupTab(app)
    %createBatchSetupTab  Build the inner tab group on the DYNAM-O
    %   Setup tab: a "File Selection" tab (data files + staging files +
    %   output dir + channel/staging-column controls) and a "DYNAM-O
    %   Settings" placeholder tab that createDYNAMOSettingsTab() then fills.

    % ---- Inner Tab Group (File Selection | DYNAM-O Settings) ----
    app.BatchRunTabGroup                = uitabgroup(app.FullDYNAMOSetupGrid);
    app.BatchRunTabGroup.Layout.Row     = 1;
    app.BatchRunTabGroup.Layout.Column  = 1;

    app.FileSelectionTab       = uitab(app.BatchRunTabGroup);
    app.FileSelectionTab.Title = 'File Selection';

    % Two-column grid: left = file + staging lists, right = runtime options
    app.FileSelectionGrid                   = uigridlayout(app.FileSelectionTab);
    app.FileSelectionGrid.ColumnWidth       = {'1x', 450};
    app.FileSelectionGrid.RowHeight         = {'1x'};
    app.FileSelectionGrid.ColumnSpacing     = 5;

    % The left column is further broken into two columns
    % 3-row grid: title + instruction | list boxes | action buttons
    icon_only_width = '60px';
    filelist_icon_size = '1.25em';
    button_height = 70;

    app.FileInputGrid                   = uigridlayout(app.FileSelectionGrid);
    app.FileInputGrid.ColumnWidth       = {'1x', '1x'};
    app.FileInputGrid.RowHeight         = {30, 20, '1x', button_height};
    app.FileInputGrid.ColumnSpacing     = 15;
    app.FileInputGrid.RowSpacing        = 0;
    app.FileInputGrid.Padding           = [5 0 10 0];
    app.FileInputGrid.Layout.Row        = 1;
    app.FileInputGrid.Layout.Column     = 1;

    % ============================================================
    %   FILE SELECTION (left column)
    % ============================================================

    app.DataLabel = CSSuiLabel(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'FontSize', app.FontSizeTitle, ...
        'Text', 'DATA (0 Files)', ...
        'HorizontalAlignment','left',...
        'VerticalAlignment','top'...
        );
    app.DataLabel.Layout.Row    = 1;
    app.DataLabel.Layout.Column = 1;

    app.DataFileInstructionText = CSSuiLabel(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'FontSize', '11.5px', ...
        'FontWeight', '700', ...
        'Text', 'ADD PSG FILES (.edf, .edf.gz, .edf.zst). DOUBLE-CLICK FILE FOR HEADER INFO.' ...
        );
    app.DataFileInstructionText.Row    = 2;
    app.DataFileInstructionText.Column = 1;

    % Double-click opens the EDF header viewer
    app.DataListBox = CSSuiListBox(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'Multiselect', true, ...
        'BackgroundColor', '#ffffff', ...
        'DoubleClickFcn', createCallbackFcn(app, @ShowHeader, true));
    app.DataListBox.Layout.Row    = 3;
    app.DataListBox.Layout.Column = 1;
    app.DataListBox.HTMLComponent.Tooltip = 'Double-click a file to view the header';

    % ---- Data File Action Buttons ----
    app.DataFileButtonGrid                  = uigridlayout(app.FileInputGrid);
    % Edge spacers are 0.2x (was 1x) so the five button cells own
    % most of the row width; combined with the bumped MaxWidth on each
    % button below, this lets the buttons grow on large monitors while
    % staying centered in their cells (MaxWidth handles centering).
    app.DataFileButtonGrid.ColumnWidth      = {'0.2x', '1x', '1x', '1x', '1x', '1x', '0.2x'};
    app.DataFileButtonGrid.RowHeight        = {button_height};
    app.DataFileButtonGrid.ColumnSpacing    = 5;
    app.DataFileButtonGrid.Padding          = [5 0 5 0];
    app.DataFileButtonGrid.Layout.Row       = 4;
    app.DataFileButtonGrid.Layout.Column    = 1;

    % -- Add single EDF file --
    app.DataAddFileButton = CSSuiButton(app.DataFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Add File', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn', createCallbackFcn(app, @DataAddFileButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon',     '<path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zm-1 7V3.5L18.5 9H13z M11 13h2v-2h2v2h2v2h-2v2h-2v-2h-2z"/>' ...
        );
    app.DataAddFileButton.Row    = 1;
    app.DataAddFileButton.Column = 2;
    app.DataAddFileButton.HTMLComponent.Tooltip       = 'Add single EDF file';

    % -- Add EDF folder --
    app.DataAddFolderButton = CSSuiButton(app.DataFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Add Folder', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @DataAddFolderButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M10 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"/><path d="M13 14h-2v-2h-2v2H7v2h2v2h2v-2h2v-2z" fill="white" opacity="0.9"/>' ...
        );
    app.DataAddFolderButton.Row    = 1;
    app.DataAddFolderButton.Column = 3;
    app.DataAddFolderButton.HTMLComponent.Tooltip       = 'Add all EDF files in folder';

    % -- Remove selected EDF file --
    app.DataRemoveButton = CSSuiButton(app.DataFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Delete File', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @DataRemoveButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M3 6h18v2H3V6zm2 2h14l-1.5 14h-11L5 8zm5 2v8h2v-8h-2zm4 0v8h2v-8h-2zM8 4h8v2H8V4z"/>' ...
        );
    app.DataRemoveButton.Row    = 1;
    app.DataRemoveButton.Column = 4;
    app.DataRemoveButton.HTMLComponent.Tooltip       = 'Remove selected EDF file';

    % -- Move EDF file up --
    app.DataMoveUpButton = CSSuiButton(app.DataFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Move Up', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn', createCallbackFcn(app, @DataMoveUpButtonPushed, true), ...
        'Padding', '15px', ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M12 5l-7 9h5v8h4v-8h5z"/>' ...
        );
    app.DataMoveUpButton.Row    = 1;
    app.DataMoveUpButton.Column = 5;
    app.DataMoveUpButton.HTMLComponent.Tooltip = 'Move current EDF file up';

    % -- Move EDF file down --
    app.DataMoveDownButton = CSSuiButton(app.DataFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Move Down', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn', createCallbackFcn(app, @DataMoveDownButtonPushed, true), ...
        'Padding', '15px', ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M12 19l-7-9h5v-8h4v8h5z"/>' ...
        );
    app.DataMoveDownButton.Row    = 1;
    app.DataMoveDownButton.Column = 6;
    app.DataMoveDownButton.HTMLComponent.Tooltip = 'Move current EDF file down';

    % =========================================================================
    %  STAGING SELECTION (middle column)
    % =========================================================================

    app.StagingLabel = CSSuiLabel(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'FontSize', app.FontSizeTitle, ...
        'VerticalAlignment', 'top',...
        'HorizontalAlignment', 'left', 'Text', 'STAGING (0 Files)' ...
        );
    app.StagingLabel.Layout.Row    = 1;
    app.StagingLabel.Layout.Column = 2;

    app.StagingFileInstructionText = CSSuiLabel(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'FontSize', '11.5px', ...
        'FontWeight', '700', ...
        'Text', 'ADD STAGING FILES (.csv/.txt). MATCH PSG FILE ORDER.' ...
        );
    app.StagingFileInstructionText.Layout.Row    = 2;
    app.StagingFileInstructionText.Layout.Column = 2;

    app.StagingListBox = CSSuiListBox(app.FileInputGrid, ...
        'Style', 'shadow_light', ...
        'Multiselect', true, ...
        'BackgroundColor', '#ffffff', ...
        'DoubleClickFcn', createCallbackFcn(app, @ShowFile, true));
    app.StagingListBox.Layout.Row    = 3;
    app.StagingListBox.Layout.Column = 2;
    app.StagingListBox.HTMLComponent.Tooltip = 'Double-click a file to view/edit';

    % ---- Staging File Action Buttons ----
    app.StagingFileButtonGrid             = uigridlayout(app.FileInputGrid);
    % Mirrors DataFileButtonGrid: trim edge spacers, give the button
    % cells more room so MaxWidth can be larger on big monitors.
    app.StagingFileButtonGrid.ColumnWidth = {'0.2x', '1x', '1x', '1x', '1x', '1x', '0.2x'};
    app.StagingFileButtonGrid.RowHeight   = {button_height};
    app.StagingFileButtonGrid.ColumnSpacing = 5;
    app.StagingFileButtonGrid.Padding     = [5 0 5 0];
    app.StagingFileButtonGrid.Layout.Row  = 4;
    app.StagingFileButtonGrid.Layout.Column = 2;

    % -- Add single staging file --
    app.StagingAddFileButton = CSSuiButton(app.StagingFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Add File', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn', createCallbackFcn(app, @StagingAddFileButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon',     '<path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zm-1 7V3.5L18.5 9H13z M11 13h2v-2h2v2h2v2h-2v2h-2v-2h-2z"/>' ...
        );
    app.StagingAddFileButton.Row    = 1;
    app.StagingAddFileButton.Column = 2;
    app.StagingAddFileButton.HTMLComponent.Tooltip       = 'Add single EDF file';

    app.StagingAddFolderButton = CSSuiButton(app.StagingFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Add Folder', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @StagingAddFolderButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M10 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"/><path d="M13 14h-2v-2h-2v2H7v2h2v2h2v-2h2v-2z" fill="white" opacity="0.9"/>' ...
        );
    app.StagingAddFolderButton.Row    = 1;
    app.StagingAddFolderButton.Column = 3;
    app.StagingAddFolderButton.HTMLComponent.Tooltip       = 'Add all staging files in folder';

    % -- Remove selected staging file --
    app.StagingRemoveButton = CSSuiButton(app.StagingFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Delete File', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @StagingRemoveButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M3 6h18v2H3V6zm2 2h14l-1.5 14h-11L5 8zm5 2v8h2v-8h-2zm4 0v8h2v-8h-2zM8 4h8v2H8V4z"/>' ...
        );
    app.StagingRemoveButton.Row    = 1;
    app.StagingRemoveButton.Column = 4;
    app.StagingRemoveButton.HTMLComponent.Tooltip       = 'Remove selected staging file';

    % -- Move staging file up --
    app.StagingMoveUpButton = CSSuiButton(app.StagingFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Move Up', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @StagingMoveUpButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M12 5l-7 9h5v8h4v-8h5z"/>' ...
        );
    app.StagingMoveUpButton.Row    = 1;
    app.StagingMoveUpButton.Column = 5;
    app.StagingMoveUpButton.HTMLComponent.Tooltip       = 'Move current staging file up';

    % -- Move staging file down --
    app.StagingMoveDownButton = CSSuiButton(app.StagingFileButtonGrid, ...
        'Style', 'shadow', ...
        'Text', 'Move Down', ...
        'MaxWidth', '180px',...
        'ButtonPushedFcn',  createCallbackFcn(app, @StagingMoveDownButtonPushed, true), ...
        'IconPosition', 'top', ...
        'IconSize', filelist_icon_size,...
        'IconOnlyWidth', icon_only_width,...
        'Icon', '<path d="M12 19l-7-9h5v-8h4v8h5z"/>' ...
        );
    app.StagingMoveDownButton.Row    = 1;
    app.StagingMoveDownButton.Column = 6;
    app.StagingMoveDownButton.HTMLComponent.Tooltip       = 'Move current staging file down';

    % ============================================================
    %   RUNTIME OPTIONS (right column)
    % ============================================================

    % Three-row right column: channel options | staging options | saving options
    app.RuntimeOptionsGrid                  = uigridlayout(app.FileSelectionGrid);
    app.RuntimeOptionsGrid.ColumnWidth      = {'1x'};
    app.RuntimeOptionsGrid.RowHeight        = {50, 35, 280, '1x', 270};
    app.RuntimeOptionsGrid.ColumnSpacing    = 0;
    app.RuntimeOptionsGrid.RowSpacing       = 0;
    app.RuntimeOptionsGrid.Padding          = [0 6 0 0];
    app.RuntimeOptionsGrid.Layout.Row       = 1;
    app.RuntimeOptionsGrid.Layout.Column    = 2;

    %Runtime Label
    app.RuntimeOptionsLabel = CSSuiLabel(app.RuntimeOptionsGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'FontSize', app.FontSizeTitle, ...
        'Text', 'INPUT SETTINGS', ...
        'VerticalAlignment','top'...
        );
    app.RuntimeOptionsLabel.Layout.Row    = 1;
    app.RuntimeOptionsLabel.Layout.Column = 1;

    % ---- Channel Selection (Row 1) ----
    app.ChannelInputGrid                   = uigridlayout(app.RuntimeOptionsGrid);
    app.ChannelInputGrid.ColumnWidth       = {'2x', '7x', '2x'};
    app.ChannelInputGrid.RowHeight         = {'1x'};
    app.ChannelInputGrid.Padding           = [0 0 0 0];
    app.ChannelInputGrid.Layout.Row        = 2;
    app.ChannelInputGrid.Layout.Column     = 1;

    app.ChannelEditFieldLabel = CSSuiLabel(app.ChannelInputGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Channel(s)' ...
        );
    app.ChannelEditFieldLabel.Layout.Row    = 1;
    app.ChannelEditFieldLabel.Layout.Column = 1;

    app.ChannelEditField               = CSSuiEditField(app.ChannelInputGrid, ...
        'Style','shadow_light', ...
        'Value', 'Enter comma-separated channel labels' ...
        );
    app.ChannelEditField.Layout.Row    = 1;
    app.ChannelEditField.Layout.Column = 2;

    % Info button: opens dialog listing all channels present in loaded EDFs
    app.ViewChannelsButton = CSSuiButton(app.ChannelInputGrid, ...
        'Style', 'shadow', ...
        'Text', 'Select' ...
        );
    app.ViewChannelsButton.Row    = 1;
    app.ViewChannelsButton.Column = 3;
    app.ViewChannelsButton.ButtonPushedFcn = createCallbackFcn(app, @viewChannelsButtonPushed, true);

    % ---- Staging Options (Row 2) ----
    % Two-sub-column panel: left = stage label identifiers, right = file format inputs
    app.StagingOptionsPanelGrid                 = uigridlayout(app.RuntimeOptionsGrid);
    app.StagingOptionsPanelGrid.ColumnWidth     = {'2x', '4x', '3x', '2x'} ;
    app.StagingOptionsPanelGrid.RowHeight       = {'1x','1x','1x','1x','1x','1x','1x'};
    app.StagingOptionsPanelGrid.ColumnSpacing   = 10;
    app.StagingOptionsPanelGrid.RowSpacing      = 0;
    app.StagingOptionsPanelGrid.Padding         = [0 5 0 5];
    app.StagingOptionsPanelGrid.Layout.Row      = 3;
    app.StagingOptionsPanelGrid.Layout.Column   = 1;

    % Artifact stage identifiers
    app.ArtifactEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Artifact' ...
        );
    app.ArtifactEditFieldLabel.Layout.Row    = 1;
    app.ArtifactEditFieldLabel.Layout.Column = 1;

    app.ArtifactEditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'artifact, A, 6' ...
        );
    app.ArtifactEditField.Layout.Row    = 1;
    app.ArtifactEditField.Layout.Column = 2;

    % Wake stage identifiers
    app.WakeEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Wake' ...
        );
    app.WakeEditFieldLabel.Layout.Row    = 2;
    app.WakeEditFieldLabel.Layout.Column = 1;

    app.WakeEditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'wake, W, 5' ...
        );
    app.WakeEditField.Layout.Row    = 2;
    app.WakeEditField.Layout.Column = 2;

    % REM stage identifiers
    app.REMEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'REM' ...
        );
    app.REMEditFieldLabel.Layout.Row    = 3;
    app.REMEditFieldLabel.Layout.Column = 1;

    app.REMEditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'REM, R, 4' ...
        );
    app.REMEditField.Layout.Row    = 3;
    app.REMEditField.Layout.Column = 2;

    % N1 stage identifiers
    app.N1EditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'N1' ...
        );
    app.N1EditFieldLabel.Layout.Row    = 4;
    app.N1EditFieldLabel.Layout.Column = 1;

    app.N1EditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'N1, Stage 1, 1' ...
        );
    app.N1EditField.Layout.Row    = 4;
    app.N1EditField.Layout.Column = 2;

    % N2 stage identifiers
    app.N2EditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'N2' ...
        );
    app.N2EditFieldLabel.Layout.Row    = 5;
    app.N2EditFieldLabel.Layout.Column = 1;

    app.N2EditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'N2, Stage 2, 2' ...
        );
    app.N2EditField.Layout.Row    = 5;
    app.N2EditField.Layout.Column = 2;

    % N3 stage identifiers
    app.N3EditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'N3' ...
        );
    app.N3EditFieldLabel.Layout.Row    = 6;
    app.N3EditFieldLabel.Layout.Column = 1;

    app.N3EditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'N3, Stage 3, 3' ...
        );
    app.N3EditField.Layout.Row    = 6;
    app.N3EditField.Layout.Column = 2;

    % Unknown stage identifiers
    app.UnknownEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Unknown' ...
        );
    app.UnknownEditFieldLabel.Layout.Row    = 7;
    app.UnknownEditFieldLabel.Layout.Column = 1;

    app.UnknownEditField = CSSuiEditField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Value', 'Unk, U, Unknown' ...
        );
    app.UnknownEditField.Layout.Row    = 7;
    app.UnknownEditField.Layout.Column = 2;

    % Stages column index
    app.StagesColumnEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Stages Column' ...
        );
    app.StagesColumnEditFieldLabel.Layout.Row    = 2;
    app.StagesColumnEditFieldLabel.Layout.Column = 3;

    app.StagesColumnEditField = CSSuiNumericField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Min', 0 ...
        );
    app.StagesColumnEditField.Layout.Row    = 2;
    app.StagesColumnEditField.Layout.Column = 4;

    % Times column index
    app.TimesColumnEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Times Column' ...
        );
    app.TimesColumnEditFieldLabel.Row    = 3;
    app.TimesColumnEditFieldLabel.Column = 3;

    app.TimesColumnEditField = CSSuiNumericField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Min', 0 ...
        );
    app.TimesColumnEditField.Row    = 3;
    app.TimesColumnEditField.Column = 4;

    % Header rows count
    app.HeaderRowsEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'Header Rows' ...
        );
    app.HeaderRowsEditFieldLabel.Row    = 4;
    app.HeaderRowsEditFieldLabel.Column = 3;

    app.HeaderRowsEditField = CSSuiNumericField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Min', 0 ...
        );
    app.HeaderRowsEditField.Row    = 4;
    app.HeaderRowsEditField.Column = 4;

    % Resample Data switch (row 6, row 5 left as a visual spacer).
    % ON by default at 100 Hz: keeps the spectrogram working set
    % within L3 cache on real-patient EDFs (typically recorded at
    % 128/200/256/500 Hz) where it would otherwise spill and slow
    % the whole pipeline ~2x. DYNAM-O analyzes 0-30 Hz so 100 Hz
    % Nyquist is well above anything we care about.
    app.ResampleSwitch = CSSuiSwitch(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow', ...
        'Text', 'Resample Data', ...
        'Value', 1 ...
        );
    app.ResampleSwitch.Layout.Row    = 6;
    app.ResampleSwitch.Layout.Column = [3 4];
    app.ResampleSwitch.ValueChangedFcn = @(~,~) app.onResampleSwitchChanged();

    % Sampling frequency field (row 7, enabled because switch is on).
    app.ResampleFsEditFieldLabel = CSSuiLabel(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Text', 'New Fs (Hz)', ...
        'Enabled', true ...
        );
    app.ResampleFsEditFieldLabel.Layout.Row    = 7;
    app.ResampleFsEditFieldLabel.Layout.Column = 3;

    app.ResampleFsEditField = CSSuiNumericField(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Min', 0, ...
        'Value', 100, ...
        'Enabled', true ...
        );
    app.ResampleFsEditField.Layout.Row    = 7;
    app.ResampleFsEditField.Layout.Column = 4;

    % File delimiter dropdown
    app.DelimeterOptionField = CSSuiDropdown(app.StagingOptionsPanelGrid, ...
        'Style', 'shadow_light', ...
        'Label', 'File Delimiter', ...
        'Items', {'Comma', 'Tab', 'Space', 'Semicolon'}, ...
        'Value', 'Comma', ...
        'FontWeight', 'normal' ...
        );
    app.DelimeterOptionField.Row    = 1;
    app.DelimeterOptionField.Column = [3 4];

    % ---- Saving Options and File Formats (Row 3) ----
    app.SavingOptionsTabGroupGrid                   = uigridlayout(app.RuntimeOptionsGrid);
    app.SavingOptionsTabGroupGrid.ColumnWidth       = {'1x'};
    app.SavingOptionsTabGroupGrid.RowHeight         = {'1x'};
    app.SavingOptionsTabGroupGrid.Padding           = [0 0 5 0];  % dedicated grid to add padding
    app.SavingOptionsTabGroupGrid.Layout.Row        = 5;
    app.SavingOptionsTabGroupGrid.Layout.Column     = 1;

    app.SavingOptionsTabGroup                   = uitabgroup(app.SavingOptionsTabGroupGrid);
    app.SavingOptionsTabGroup.Layout.Row        = 1;
    app.SavingOptionsTabGroup.Layout.Column     = 1;

    % ============================================================
    %   SAVING OPTIONS TAB
    % ============================================================

    app.SavingOptionsTab       = uitab(app.SavingOptionsTabGroup);
    app.SavingOptionsTab.Title = 'Saving Options';
    app.SavingOptionsTabGroup.SelectedTab = app.SavingOptionsTab;

    app.SavingOptionsTabGrid             = uigridlayout(app.SavingOptionsTab);
    app.SavingOptionsTabGrid.ColumnWidth = {'1x'};
    app.SavingOptionsTabGrid.RowHeight   = {'3x', '1x'};
    app.SavingOptionsTabGrid.RowSpacing  = 0;
    app.SavingOptionsTabGrid.Padding     = [10 0 5 2];

    % Six-row, two-column grid of save checkboxes
    app.SavingOptionsCheckBoxGrid             = uigridlayout(app.SavingOptionsTabGrid);
    app.SavingOptionsCheckBoxGrid.ColumnWidth = {'1x', '1x'};
    app.SavingOptionsCheckBoxGrid.RowHeight   = {'1x','1x','1x','1x','1x','1x'};
    app.SavingOptionsCheckBoxGrid.Padding     = [3 5 3 5];
    app.SavingOptionsCheckBoxGrid.Layout.Row  = 1;
    app.SavingOptionsCheckBoxGrid.Layout.Column = 1;

    % Column headers
    app.DatatoSaveLabel = CSSuiLabel(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'Text', 'DATA TO SAVE' ...
        );
    app.DatatoSaveLabel.Layout.Row    = 1;
    app.DatatoSaveLabel.Layout.Column = 1;

    app.FigurestoSaveLabel = CSSuiLabel(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'Text', 'FIGURES TO SAVE' ...
        );
    app.FigurestoSaveLabel.Layout.Row    = 1;
    app.FigurestoSaveLabel.Layout.Column = 2;

    % --- Data Tables (Left Column) ---
    app.SavePeakStatsCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Peak Stats Tables', ...
        'Value', 1 ...
        );
    app.SavePeakStatsCheckBox.Row    = 2;
    app.SavePeakStatsCheckBox.Column = 1;
    app.SavePeakStatsCheckBox.HTMLComponent.Tooltip       = 'Save TFpeak stats tables, which store individual peak features for all detected TFpeaks';

    app.SaveSOPHsCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'SO-Power Histogram', ...
        'Value', 1 ...
        );
    app.SaveSOPHsCheckBox.Row    = 3;
    app.SaveSOPHsCheckBox.Column = 1;
    app.SaveSOPHsCheckBox.HTMLComponent.Tooltip       = 'Save SO-power and SO-phase histograms';

    app.SaveParamBasisCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Parametric Basis', ...
        'Value', 1 ...
        );
    app.SaveParamBasisCheckBox.Row    = 4;
    app.SaveParamBasisCheckBox.Column = 1;
    app.SaveParamBasisCheckBox.HTMLComponent.Tooltip       = 'Save tables of estimated mode feature parameters for SO-power and SO-phase histograms';

    app.SaveSplineBasisCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Spline Basis', ...
        'Value', 1 ...
        );
    app.SaveSplineBasisCheckBox.Row    = 5;
    app.SaveSplineBasisCheckBox.Column = 1;
    app.SaveSplineBasisCheckBox.HTMLComponent.Tooltip       = 'Save matrix of spline knot parameters';

    app.SaveAuxDataCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Auxiliary Data', ...
        'Value', 1 ...
        );
    app.SaveAuxDataCheckBox.Row    = 6;
    app.SaveAuxDataCheckBox.Column = 1;
    app.SaveAuxDataCheckBox.HTMLComponent.Tooltip       = 'Save auxiliary data helpful for rapid recomputation and figure generation without accessing the raw data';

    app.SaveLogsSwitch = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Save Logs', ...
        'Value', 1 ...
        );
    app.SaveLogsSwitch.Row    = 6;
    app.SaveLogsSwitch.Column = 2;
    app.SaveLogsSwitch.HTMLComponent.Tooltip = 'Save run log and settings files to the output logs/ and settings/ directories';

    % --- Figure Save Checkboxes (Right Column) ---
    app.SaveDataSummaryCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Data Summary', ...
        'Value', 1 ...
        );
    app.SaveDataSummaryCheckBox.Row    = 2;
    app.SaveDataSummaryCheckBox.Column = 2;
    app.SaveDataSummaryCheckBox.HTMLComponent.Tooltip       = 'Save DYNAM-O summary figures, showing spectrogram, SO-power, detected peaks, and SO-power/phase histograms';

    app.SaveParamImagesCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Parametric Basis', ...
        'Value', 1 ...
        );
    app.SaveParamImagesCheckBox.Row    = 3;
    app.SaveParamImagesCheckBox.Column = 2;
    app.SaveParamImagesCheckBox.HTMLComponent.Tooltip       = 'Save the output figures for parametric fits';

    app.SaveSplineImagesCheckBox = CSSuiSwitch(app.SavingOptionsCheckBoxGrid, ...
        'Style', 'shadow', ...
        'Text', 'Spline Basis', ...
        'Value', 1 ...
        );
    app.SaveSplineImagesCheckBox.Row    = 4;
    app.SaveSplineImagesCheckBox.Column = 2;
    app.SaveSplineImagesCheckBox.HTMLComponent.Tooltip       = 'Save the output figures for spline fits';

    % ---- Output Directory Row ----
    app.SavingDirectoryGrid             = uigridlayout(app.SavingOptionsTabGrid);
    app.SavingDirectoryGrid.ColumnWidth = {'8x', '2x'};
    app.SavingDirectoryGrid.RowHeight   = {'2x', '4x'};
    app.SavingDirectoryGrid.RowSpacing  = 0;
    app.SavingDirectoryGrid.Padding     = [5 5 5 0];
    app.SavingDirectoryGrid.Layout.Row  = 2;
    app.SavingDirectoryGrid.Layout.Column = 1;

    app.OutputDirLabel = CSSuiLabel(app.SavingDirectoryGrid, ...
        'Style', 'shadow_light', ...
        'FontSize', '12px', ...
        'Text', 'Select output directory:' ...
        );
    app.OutputDirLabel.Layout.Row    = 1;
    app.OutputDirLabel.Layout.Column = 1;

    app.OutputDirButton = CSSuiButton(app.SavingDirectoryGrid, ...
        'Style', 'shadow', ...
        'Text', 'Browse', ...
        'ButtonPushedFcn', @(src,event) browseOutputDir(app) ...
        );
    app.OutputDirButton.Row    = 2;
    app.OutputDirButton.Column = 2;

    % Placeholder label under the edit field (edit field renders on top)
    app.EditFieldLabel = CSSuiLabel(app.SavingDirectoryGrid, 'Text', 'Edit Field');
    app.EditFieldLabel.Layout.Row    = 2;
    app.EditFieldLabel.Layout.Column = 1;

    app.OutputDirEditField = CSSuiEditField(app.SavingDirectoryGrid, 'style','shadow_light');
    app.OutputDirEditField.Layout.Row    = 2;
    app.OutputDirEditField.Layout.Column = 1;
    app.OutputDirEditField.HTMLComponent.Tooltip = 'Select the root directory from which to generate the output file structure';

    % ============================================================
    %   FILE FORMAT TAB
    % ============================================================

    app.FileFormatTab       = uitab(app.SavingOptionsTabGroup);
    app.FileFormatTab.Title = 'File Formats';
    app.SavingOptionsTabGroup.SelectedTab = app.FileFormatTab;

    app.FileFormatCheckBoxGrid                = uigridlayout(app.FileFormatTab);
    app.FileFormatCheckBoxGrid.ColumnWidth    = {'1x', '1x', '1x', '1x'};
    app.FileFormatCheckBoxGrid.RowHeight = {30,30,30,30,30,30,30};
    app.FileFormatCheckBoxGrid.ColumnSpacing      = 0;

    % ----- Column headers -----
    app.DataFileFormatLabel = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'Text', 'DATA FILE FORMAT' ...
        );
    app.DataFileFormatLabel.Layout.Row    = 1;
    app.DataFileFormatLabel.Layout.Column = [1 2];

    app.FigureFileFormatLabel = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'FontWeight', '700', ...
        'Text', 'FIGURE FILE FORMAT' ...
        );
    app.FigureFileFormatLabel.Layout.Row    = 1;
    app.FigureFileFormatLabel.Layout.Column = [3 4];

    % ----- Data column dropdowns (col 1) -----
    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Peak Stats Table' ...
        );
    lab.Row    = 2;
    lab.Column = 1;

    app.PeakStatsTableDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.csv', '.mat', 'All'}, ...
        'Value',         '.csv' ...
        );
    app.PeakStatsTableDropDown.Row    = 2;
    app.PeakStatsTableDropDown.Column = 2;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'SO Histograms' ...
        );
    lab.Row    = 3;
    lab.Column = 1;

    app.SOPowerHistogramsDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.tiff', '.mat', 'All'}, ...
        'Value',         '.tiff' ...
        );
    app.SOPowerHistogramsDropDown.Row    = 3;
    app.SOPowerHistogramsDropDown.Column = 2;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Parametric Basis' ...
        );
    lab.Row    = 4;
    lab.Column = 1;

    app.ParametricBasisDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.csv', '.mat', 'All'}, ...
        'Value',         '.csv' ...
        );
    app.ParametricBasisDropDown.Row    = 4;
    app.ParametricBasisDropDown.Column = 2;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Spline Basis' ...
        );
    lab.Row    = 5;
    lab.Column = 1;

    app.SplineBasisDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.tiff', '.mat', 'All'}, ...
        'Value',         '.mat' ...
        );
    app.SplineBasisDropDown.Row    = 5;
    app.SplineBasisDropDown.Column = 2;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Auxiliary Data' ...
        );
    lab.Row    = 6;
    lab.Column = 1;

    app.AuxiliaryDataDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'.mat', '--'}, ...
        'Value',         '.mat' ...
        );
    app.AuxiliaryDataDropDown.Row    = 6;
    app.AuxiliaryDataDropDown.Column = 2;

    % ----- Figure column dropdowns (col 2) -----
    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Data Summaries' ...
        );
    lab.Row    = 2;
    lab.Column = 3;

    app.DataSummaryDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.png', '.jpg', '.jpeg'}, ...
        'Value',         '.png' ...
        );
    app.DataSummaryDropDown.Row    = 2;
    app.DataSummaryDropDown.Column = 4;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Parametric Fits' ...
        );
    lab.Row    = 3;
    lab.Column = 3;

    app.ParametricFiguresDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.png', '.jpg', '.jpeg'}, ...
        'Value',         '.png' ...
        );
    app.ParametricFiguresDropDown.Row    = 3;
    app.ParametricFiguresDropDown.Column = 4;

    lab = CSSuiLabel(app.FileFormatCheckBoxGrid, ...
        'Style', 'shadow_light', ...
        'Text' , 'Spline Fits' ...
        );
    lab.Row    = 4;
    lab.Column = 3;

    app.SplineFiguresDropDown = CSSuiDropdown(app.FileFormatCheckBoxGrid, ...
        'Style','shadow_light', ...
        'DropdownWidth', '4.25em', ...
        'Items',         {'--', '.png', '.jpg', '.jpeg'}, ...
        'Value',         '.png' ...
        );
    app.SplineFiguresDropDown.Row    = 4;
    app.SplineFiguresDropDown.Column = 4;

    app.SavingOptionsTabGroup.SelectedTab = app.SavingOptionsTab;

    % ============================================================
    %   DYNAM-O SETTINGS TAB
    % ============================================================

    app.DYNAMOSettingsTab       = uitab(app.BatchRunTabGroup);
    app.DYNAMOSettingsTab.Title = 'DYNAM-O Settings';

    app.DYNAMOSettingsGrid         = uigridlayout(app.DYNAMOSettingsTab);
    app.DYNAMOSettingsGrid.ColumnWidth = {'1x'};
    app.DYNAMOSettingsGrid.RowHeight   = {'1x'};

    % ============================================================
    %   BOTTOM BAR (Status | Run buttons | Options + Progress)
    % ============================================================

    % Three equal-flex columns: status | STOP/RUN/toggles row |
    % progress bar + Help. The middle column hosts RunBatchGrid
end
