function createResultsBrowserTab(app)
    %createResultsBrowserTab  Build the Results Browser tab: header,
    %   directory picker, file tree, status pane, and right-side preview
    %   pane with the splitter handle between them.
    % ============================================================
    %   RESULTS BROWSER TAB
    % ============================================================
    % Outer 1x1 grid so the contents scale with the tab.
    app.ResultsBrowserGrid             = uigridlayout(app.ResultsBrowserTab);
    app.ResultsBrowserGrid.ColumnWidth = {'1x'};
    app.ResultsBrowserGrid.RowHeight   = {'1x'};
    app.ResultsBrowserGrid.Padding     = 10;

    % 1x3 split: left column | draggable splitter (6 px) | right.
    % User-draggable splitter — see beginColumnResize().
    app.BrowserContentContainer                 = uigridlayout(app.ResultsBrowserGrid);
    app.BrowserContentContainer.ColumnWidth     = {'1.2x', 6, '3x'};
    app.BrowserContentContainer.RowHeight       = {'1x'};
    app.BrowserContentContainer.ColumnSpacing   = 4;
    app.BrowserContentContainer.Padding         = [0 0 0 0];
    app.BrowserContentContainer.Layout.Row      = 1;
    app.BrowserContentContainer.Layout.Column   = 1;

    % --- Splitter handle (column 2) ----------------------------------
    app.ResultsSplitter = uipanel(app.BrowserContentContainer, ...
        'BorderType','line', ...
        'BorderColor', [0.78 0.80 0.83], ...
        'BackgroundColor', [0.92 0.93 0.95]);
    app.ResultsSplitter.Layout.Row    = 1;
    app.ResultsSplitter.Layout.Column = 2;
    app.ResultsSplitter.ButtonDownFcn = @(~,~) app.beginColumnResize();
    app.ResultsSplitter.Tooltip = ...
        'Drag to resize the tree pane vs the preview pane';

    % Left column: dir label + edit field + browse + load + tree.
    app.ResultsLeftGrid             = uigridlayout(app.BrowserContentContainer);
    app.ResultsLeftGrid.ColumnWidth = {'8x','2x'};
    % Rows: header | dir-label | dir-field+browse | tree-label
    %     | tree | row-splitter (drag) | status
    % Tree:status flex ratio mirrors the batch setup's main:bottom
    % ratio ('20x':'3x' on FullDYNAMOSetupGrid). Browse button
    % needs a slightly taller row so its drop shadow doesn't clip.
    app.ResultsLeftGrid.RowHeight   = {28, 20, 38, 20, '20x', 6, '3x'};
    app.ResultsLeftGrid.RowSpacing  = 5;
    app.ResultsLeftGrid.Padding     = [0 0 0 0];
    app.ResultsLeftGrid.Layout.Row    = 1;
    app.ResultsLeftGrid.Layout.Column = 1;

    % --- Header (row 1) -------------------------------------------------
    app.ResultsBrowserHeader = CSSuiLabel(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'FontSize', app.FontSizeTitle, ...
        'FontWeight','700', ...
        'Text','RESULTS BROWSER');
    app.ResultsBrowserHeader.Layout.Row    = 1;
    app.ResultsBrowserHeader.Layout.Column = [1 2];
    app.ResultsBrowserHeader.HTMLComponent.Tooltip = ...
        'Browse and visualize completed DYNAM-O run outputs';

    app.ResultsBrowserOutputDirLabel = CSSuiLabel(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'FontSize','12px', ...
        'Text','Select results directory:');
    app.ResultsBrowserOutputDirLabel.Layout.Row    = 2;
    app.ResultsBrowserOutputDirLabel.Layout.Column = [1 2];
    app.ResultsBrowserOutputDirLabel.HTMLComponent.Tooltip = ...
        'Pick a DYNAM-O_results folder produced by a batch run';

    app.ResultsBrowserOutputDirField = CSSuiEditField(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'Value','', ...
        'ValueChangedFcn', @(src,evt) loadResultsBrowserTree(app));
    app.ResultsBrowserOutputDirField.Layout.Row    = 3;
    app.ResultsBrowserOutputDirField.Layout.Column = 1;
    app.ResultsBrowserOutputDirField.HTMLComponent.Tooltip = ...
        'Path to a DYNAM-O_results folder. Press Enter to load.';

    app.ResultsBrowserOutputDirButton = CSSuiButton(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'Text','Browse', ...
        'MaxWidth','120px', ...
        'MaxHeight','36px', ...
        'BoxShadow','2px 2px 4px rgba(0,0,0,0.18),-2px -2px 4px rgba(255,255,255,0.9)', ...
        'ButtonPushedFcn', @(src,evt) browseResultsBrowserDir(app));
    app.ResultsBrowserOutputDirButton.Layout.Row    = 3;
    app.ResultsBrowserOutputDirButton.Layout.Column = 2;
    app.ResultsBrowserOutputDirButton.HTMLComponent.Tooltip = ...
        'Pick a results folder. Tree loads automatically on selection.';

    app.ResultsBrowserTreeLabel = CSSuiLabel(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'FontSize', app.FontSizeTitle, ...
        'FontWeight','700', ...
        'Text','DATASET FILE TREE');
    app.ResultsBrowserTreeLabel.Layout.Row    = 4;
    app.ResultsBrowserTreeLabel.Layout.Column = [1 2];
    app.ResultsBrowserTreeLabel.HTMLComponent.Tooltip = ...
        'All folders and files under the selected results root';

    % CSSuiTree — single HTML/JS component containing both the
    % filter bar and the tree. Rendering and filtering are
    % entirely client-side; only data load and click events
    % cross the MATLAB↔JS bridge.
    app.ResultsBrowserTree = CSSuiTree(app.ResultsLeftGrid, ...
        'Style', app.AppStyle, ...
        'SearchPlaceholder','Filter by subject/filename…', ...
        'NodeClickedFcn',       @(src,evt) previewResultsBrowserNode(app, evt), ...
        'NodeDoubleClickedFcn', @(src,evt) openResultsBrowserNode(app, evt), ...
        'MenuActionFcn',        @(src,evt) onResultsBrowserMenuAction(app, evt));
    app.ResultsBrowserTree.Layout.Row    = 5;
    app.ResultsBrowserTree.Layout.Column = [1 2];
    app.ResultsBrowserTree.HTMLComponent.Tooltip = ...
        ['Click a file to preview it • double-click a file to open it ' ...
         'in the system app • right-click for context actions ' ...
         '(open, aggregate channel/paramfit/SOPHs)'];

    % Loading overlay: a uihtml stacked in the same grid cell as the
    % tree, hidden by default. While the tree loads, loadResultsBrowserTree
    % flips Visible='on' and the dancing-bars animation appears in place
    % of the tree contents. Stays in the same grid cell so layout doesn't
    % reflow when toggled.
    app.ResultsTreeLoadingOverlay = uihtml(app.ResultsLeftGrid, ...
        'Visible', 'off');
    app.ResultsTreeLoadingOverlay.Layout.Row    = 5;
    app.ResultsTreeLoadingOverlay.Layout.Column = [1 2];

    % Horizontal splitter (drag to resize tree vs status heights).
    app.ResultsRowSplitter = uipanel(app.ResultsLeftGrid, ...
        'BorderType','line', ...
        'BorderColor', [0.78 0.80 0.83], ...
        'BackgroundColor', [0.92 0.93 0.95]);
    app.ResultsRowSplitter.Layout.Row    = 6;
    app.ResultsRowSplitter.Layout.Column = [1 2];
    app.ResultsRowSplitter.ButtonDownFcn = @(~,~) app.beginRowResize();
    app.ResultsRowSplitter.Tooltip = ...
        'Drag to resize the tree vs the status pane';

    % Status sub-grid mirrors the batch-setup style: label row + text-area row.
    app.ResultsBrowserStatusGrid             = uigridlayout(app.ResultsLeftGrid);
    app.ResultsBrowserStatusGrid.ColumnWidth = {'1x'};
    app.ResultsBrowserStatusGrid.RowHeight   = {18, '1x'};
    app.ResultsBrowserStatusGrid.ColumnSpacing = 0;
    app.ResultsBrowserStatusGrid.RowSpacing  = 2;
    app.ResultsBrowserStatusGrid.Padding     = [0 0 0 0];
    app.ResultsBrowserStatusGrid.Layout.Row    = 7;
    app.ResultsBrowserStatusGrid.Layout.Column = [1 2];

    app.ResultsBrowserStatusLabel = CSSuiLabel(app.ResultsBrowserStatusGrid, ...
        'Style', app.AppStyle, ...
        'FontSize','13px', ...
        'Text','STATUS:');
    app.ResultsBrowserStatusLabel.Layout.Row    = 1;
    app.ResultsBrowserStatusLabel.Layout.Column = 1;
    app.ResultsBrowserStatusLabel.HTMLComponent.Tooltip = ...
        'Streaming log of load and aggregate operations';

    app.ResultsBrowserTextArea = CSSuiTextArea(app.ResultsBrowserStatusGrid, ...
        'Style', app.AppStyle, ...
        'Editable',false, ...
        'Color','#414c57', ...
        'FontWeight','600', ...
        'BackgroundColor','#ffffff');
    app.ResultsBrowserTextArea.Scroll = true;
    app.ResultsBrowserTextArea.Row    = 2;
    app.ResultsBrowserTextArea.Column = 1;
    app.ResultsBrowserTextArea.HTMLComponent.Tooltip = ...
        'Streaming log mirrored to the MATLAB console; auto-scrolls on new lines';
    app.ResultsBrowserTextArea.Value  = ...
        {'Pick a results folder via Browse to load it.'};

    % ============================================================
    %   Right column of Results Browser: preview pane that
    %   updates on tree click (images, TIFFs, CSV tables…).
    % ============================================================
    app.ResultsBrowserPreviewGrid             = uigridlayout(app.BrowserContentContainer);
    app.ResultsBrowserPreviewGrid.ColumnWidth = {'1x'};
    app.ResultsBrowserPreviewGrid.RowHeight   = {24, '1x'};
    app.ResultsBrowserPreviewGrid.RowSpacing  = 4;
    app.ResultsBrowserPreviewGrid.Padding     = [0 0 0 0];
    app.ResultsBrowserPreviewGrid.Layout.Row    = 1;
    app.ResultsBrowserPreviewGrid.Layout.Column = 3;

    app.ResultsBrowserPreviewTitle = CSSuiLabel(app.ResultsBrowserPreviewGrid, ...
        'Style', app.AppStyle, ...
        'FontSize', app.FontSizeTitle, ...
        'FontWeight','700', ...
        'Text','PREVIEW');
    app.ResultsBrowserPreviewTitle.Layout.Row    = 1;
    app.ResultsBrowserPreviewTitle.Layout.Column = 1;

    app.ResultsBrowserPreviewBody = uipanel(app.ResultsBrowserPreviewGrid, ...
        'BackgroundColor','white', ...
        'BorderType','line', ...
        'HighlightColor',[0.85 0.85 0.85]);
    app.ResultsBrowserPreviewBody.Layout.Row    = 2;
    app.ResultsBrowserPreviewBody.Layout.Column = 1;
    app.renderResultsBrowserPreviewPlaceholder('empty');

end
