function promptToSeedRunIndex(app, root)
    %PROMPTTOSEEDRUNINDEX  No JSONL in <root>/_runs/ — offer to
    %   seed one from the in-memory cache (the tree walker already
    %   visited every file, so no second disk pass is needed). Only
    %   called from loadResultsBrowserTree when readRunIndexFile
    %   returned false.
    try
        runsDir = fullfile(root, '_runs');
        sel = uiconfirm(app.UIFigure, ...
            sprintf(['No run index was found at:\n  %s\n\n' ...
                     'A run index catalogs every (subject, channel) so the ' ...
                     'browser can answer "what''s computed?" without ' ...
                     're-walking the tree. Generate one now from the existing files?'], ...
                     runsDir), ...
            'Generate run index?', ...
            'Options', {'Generate', 'Skip'}, ...
            'DefaultOption', 1, ...
            'CancelOption', 2, ...
            'Icon', 'question');
        if strcmp(sel, 'Generate')
            app.regenerateRunIndex(root);
        end
    catch ME
        app.logResultsBrowser(['Run-index prompt failed: ', ME.message]);
    end
end
